/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/Admin1stStartPage': RouteRecordInfo<
      '/Admin1stStartPage',
      '/Admin1stStartPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/AdminConfigPage': RouteRecordInfo<
      '/AdminConfigPage',
      '/AdminConfigPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/AdminDashboardPage': RouteRecordInfo<
      '/AdminDashboardPage',
      '/AdminDashboardPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/AdminFilesPage': RouteRecordInfo<
      '/AdminFilesPage',
      '/AdminFilesPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/AdminHelpPage': RouteRecordInfo<
      '/AdminHelpPage',
      '/AdminHelpPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/AdminLogsPage': RouteRecordInfo<
      '/AdminLogsPage',
      '/AdminLogsPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/AdminMulticamPage': RouteRecordInfo<
      '/AdminMulticamPage',
      '/AdminMulticamPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ErrorNotFound': RouteRecordInfo<
      '/ErrorNotFound',
      '/ErrorNotFound',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/GalleryDetailPage': RouteRecordInfo<
      '/GalleryDetailPage',
      '/GalleryDetailPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/GalleryPage': RouteRecordInfo<
      '/GalleryPage',
      '/GalleryPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/IndexPage': RouteRecordInfo<
      '/IndexPage',
      '/IndexPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/LoginPage': RouteRecordInfo<
      '/LoginPage',
      '/LoginPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/SlideshowPage': RouteRecordInfo<
      '/SlideshowPage',
      '/SlideshowPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/Admin1stStartPage.vue': {
      routes:
        | '/Admin1stStartPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/AdminConfigPage.vue': {
      routes:
        | '/AdminConfigPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/AdminDashboardPage.vue': {
      routes:
        | '/AdminDashboardPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/AdminFilesPage.vue': {
      routes:
        | '/AdminFilesPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/AdminHelpPage.vue': {
      routes:
        | '/AdminHelpPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/AdminLogsPage.vue': {
      routes:
        | '/AdminLogsPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/AdminMulticamPage.vue': {
      routes:
        | '/AdminMulticamPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ErrorNotFound.vue': {
      routes:
        | '/ErrorNotFound'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/GalleryDetailPage.vue': {
      routes:
        | '/GalleryDetailPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/GalleryPage.vue': {
      routes:
        | '/GalleryPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/IndexPage.vue': {
      routes:
        | '/IndexPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/LoginPage.vue': {
      routes:
        | '/LoginPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/SlideshowPage.vue': {
      routes:
        | '/SlideshowPage'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
